name: Upload NuGet package

env:
  project: CalculatedCharacteristics
on: 
  workflow_dispatch:
    inputs:
      nuget-version:
        description: 'Define optional nuget version. This can be used to create alpha versions.'
        required: false
        default: 'default'
  
defaults:
  run:
    working-directory: src

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use.
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}     
      - name: Create the package
        if: ${{github.event.inputs.nuget-version == 'default'}}
        run: dotnet pack --configuration Release ${{env.project}}
      - name: Create the package with custom version ${{github.event.inputs.nuget-version}}
        if: ${{github.event.inputs.nuget-version != 'default'}}
        run: dotnet pack --configuration Release -p:PackageVersion=${{github.event.inputs.nuget-version}} ${{env.project}}
      - name: Publish the package to NuGet
        run: dotnet nuget push ${{env.project}}/bin/Release/*.nupkg
